create table
  public.potions (
    id integer generated by default as identity,
    inventory integer null default 0,
    sku text null,
    price integer null default 50,
    potion_type integer[] null default '{}'::integer[],
    name text null,
    constraint potions_pkey primary key (id),
    constraint potions_id_key unique (id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    num_red_ml integer null,
    gold integer not null,
    num_blue_ml integer null,
    num_green_ml integer null,
    num_dark_ml integer null,
    num_red_potions integer null,
    num_green_potions integer null,
    num_blue_potions integer null,
    num_dark_potions integer null,
    constraint global_inventory_pkey primary key (gold)
  ) tablespace pg_default;

  create table
  public.carts (
    id integer generated by default as identity,
    customer text null,
    constraint carts_pkey primary key (id),
    constraint carts_id_key unique (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id integer generated by default as identity,
    carts_id integer null,
    potions_id integer null,
    quantity integer null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_carts_id_fkey foreign key (carts_id) references carts (id) on update cascade on delete cascade,
    constraint cart_items_potions_id_fkey foreign key (potions_id) references potions (id) on update cascade on delete cascade
  ) tablespace pg_default;